# Generated by Django 5.2.4 on 2026-01-27 05:30

import collect.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loop",
            name="bags",
            field=models.FloatField(
                help_text="🎒🎒🎒🎒", validators=[collect.validators.validate_bags]
            ),
        ),
        migrations.AlterField(
            model_name="loop",
            name="wage",
            field=models.IntegerField(help_text="$$$"),
        ),
    ]
